### ISSUE TITLE
HANDS STUCK WITH PHONE

### ISSUE THREAD

**Issue by xjevii** [Qbox-project/qbx-phone#7]
### Summary

I'm currently new in doing some scripts. I used your repo, Qb-phone and somehow, everytime I use the phone, the hands gets stuck.

### Reproduction

1. Using the phone. 
2. when you close the phone the hands get stuck 

### Expected behavior

Expecting the hands gets to normal

### Actual behavior

hands get stuck near the pockets

### Additional context

error code: @qb-phone/client/main.lua:541: attempt to index a nil value (global 'cache')

### Last Updated

today

### Custom Resources

no

### Resource Rename

no

**Comment by JoeSzymkowiczFiveM** [comment]
From the error, it seems like you might not have ox-lib installed and/or started.

**Comment by Manason** [comment]
Install ox_lib
